spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: PK_Users
  application:
    name: Backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
Twilio:
  SID: ${SID}
  ID: ${ID}
  NUMBER: ${NUMBER}

Jwt:
  KEY: ${KEY}
